### ISSUE TITLE
Error: During Indexing

### ISSUE THREAD

**Issue by sducamp** [mkusher/padawan.vim#1]
Hi, I have this error during the installation:
`Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.`
and during the indexation:
`Error detected while processing function padawan#GenerateIndex:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'client' is not defined`

**Comment by mkusher** [comment]
hi!
The first problem is a warning produced by composer for one of the symfony components, don't worry about it.
The second one isn't normal, do you get error after calling:

``` vim
:call padawan#StartServer()
```

?

**Comment by sducamp** [comment]
Yes I have it after 

```
:call padawan#StartServer()
```

or 

```
:call padawan#GenerateIndex()
```

Also I see in or requirements at 3. Vim with +python what is +python?
Thank you

**Comment by mkusher** [comment]
@sducamp 
Try running this command in your

``` vim
:echo has("python")
```

if it print 1, then you have vim compiled with python support. It's required for this plugin

**Comment by sducamp** [comment]
I have 1

**Comment by mkusher** [comment]
Right now I have no idea why you have this error message. So, try restarting your vim

**Comment by sducamp** [comment]
I need Padawan.php ?

**Comment by mkusher** [comment]
@sducamp yes, padawan.vim depends on it. It is included in the repo as a git submodule
Can you post your vimrc to the gist or something like it?

**Comment by mkusher** [comment]
@sducamp also try updating padawan.vim, I've fixed some bugs in installation process and added install.sh script

**Comment by sducamp** [comment]
Hi @mkusher 
Sorry but I always have the same problem.
Do you have a sample project which I can try your plugin?

**Comment by mkusher** [comment]
@sducamp can you post your vimrc, so I can try debugging?

**Comment by sducamp** [comment]
@mkusher you can find it here https://github.com/sducamp/dotfiles/blob/master/.vimrc

**Comment by mkusher** [comment]
@sducamp I've done small modifications(removed omnifunc for phpcomplete_extended and padawan.php plugin) to your vimrc and it worked perfectly:
https://gist.github.com/mkusher/ee36cdc6137e9d73c787

After `:PluginInstall` you had to manually run `install.sh` in the padawan.vim folder, because Vundle doesn't support "after install" hooks like [vim-plug](https://github.com/junegunn/vim-plug#post-update-hooks)

Can you try it with updated vimrc?

**Comment by sducamp** [comment]
Hi @mkusher , I have updated my vimrc, cleaned plugins, updated plugins, installed plugins after that I launch sh ~/.vim/bundle/padawan/install.sh everything works but I always have the same problem in Vim.
After :call padawan#GenerateIndex() I have this error

```
Error detected while processing function padawan#GenerateIndex:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'client' is not defined 
```

It's possible that my project the problem? 
What can of project do you use to try ?

**Comment by mkusher** [comment]
@sducamp it's not a php project bug, but a padawan.vim bug. Padawan.vim can be used with any composer project, Symfony2 SE for example. Some why client variable in vim functions is not accessible(or defined). So, that is not connected to vimrc configuration, maybe it's some compile option. I'll try to find solution for it.
Can you provide your system info?(OS, which vim package is used)

**Comment by sducamp** [comment]
It's a MacOs 10.10.4 and I use Vundle.
I use MacVim installed with brew.
Let me now if you need more informations.

**Comment by mkusher** [comment]
@sducamp how have you installed vim? Using brew and what package have you installed?

**Comment by sducamp** [comment]
cmake
ctags
icu4c
macvim
php56
unixodbc
composer
freetype
jpeg
openssl
readline
xz
cscope
gettext
libpng
pcre
the_silver_searcher

**Comment by mkusher** [comment]
@sducamp try updating padawan.vim, I've a restructured it, so you should be able to run it

**Comment by sducamp** [comment]
@mkusher it works !
Nice job !
Thank you
