### ISSUE TITLE
This VIM plugin sends raw JSON to the padawan-server instead of HTTP requests.

### ISSUE THREAD

**Issue by Neopallium** [mkusher/padawan.vim#13]
This plugin seems to be incompatible with the padawan-server.  The server uses HTTP, but this plugin just sends JSON messages over a raw TCP socket.

**Comment by mkusher** [comment]
@Neopallium hi, new version(master after https://github.com/mkusher/padawan.php/commit/cb2c73679c4bee0f4e77754bf2fa9b19f51bd3a2) of padawan uses raw tcp socket. If you want to use old padawan you need to check out version before https://github.com/mkusher/padawan.vim/commit/a474270fc9e6efa43bfad417716024452d24dd65

**Comment by Neopallium** [comment]
I installed the padawan server using composer like the project's page shows:

`$ composer global require mkusher/padawan`

Which installed v0.2.1 that is still using HTTP.  When someone follows the instructions for installing padawan.php & padawan.vim, they will get versions that are not compatible.

Can you create a new release of the server or put a note about the incompatible interfaces.

Also your sublime plugin is still using HTTP.

**Comment by mkusher** [comment]
yeah, you're right, need to downgrade padawan.vim's master, since I'm not ready to mark current padawan.php as stable enough for 0.3 version
