### ISSUE TITLE
Problem with generating index, "Fatal error: Allowed memory size of xxx bytes"

### ISSUE THREAD

**Issue by pklebba** [mkusher/padawan.vim#17]
When I tried generate index using :PadawanGenerateIndex, I'm getting 255 error, just like in #15 issue.

So, I tried generate using `padawan generate` command. But I'm getting: `Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 10 bytes)`

How can I fix it?

**Comment by pklebba** [comment]
I changed `memory_limit` to `-1`. And i got THIS: http://puu.sh/piIBo/809aa8a545.png

Memory leak?

**Comment by mkusher** [comment]
@Siprah hello. It looks strange, I'm not sure what is causing the issue. It is bug of padawan.php and not bug of padawan.vim, so let's continue discussion there https://github.com/mkusher/padawan.php/issues/47
