### ISSUE TITLE
Installation didn't work

### ISSUE THREAD

**Issue by EwanValentine** [mkusher/padawan.vim#2]
I cloned the plugin into my plugins directory and added the line starting `Plugin` into my ~/.vimrc file, however my vim doesn't pick up on the plugin. I'm using this Vim set-up https://github.com/amix/vimrc

**Comment by mkusher** [comment]
@EwanValentine if you use pathongen, then you shouldn't add lines with `Plugin` or so. Did you read this paragraph https://github.com/mkusher/padawan.vim#pathogen ?

**Comment by mkusher** [comment]
@EwanValentine have you installed vim with python support? `:echo has("python")` should print 1

**Comment by EwanValentine** [comment]
My bad! I was using the Plugin directive when I shouldn't have been. Got it working now, what an amazing plug-in, thanks you!!

**Comment by mkusher** [comment]
:+1:

**Comment by EwanValentine** [comment]
@mkusher Apologies, I'm having issues again. I've ran `:PadawanGenerateIndex` and `:PadawanStartServer`, I've got triggers mapped for expressions such as `->` etc as suggested. However, I get a message ':Padawan is not running' or 'timed out'.

**Comment by EwanValentine** [comment]
`:echo has("python")` evaluates as 1 also

**Comment by EwanValentine** [comment]
Bit more info, when I tried to run the server manually, I got 

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /Users/EwanValentine/.vim_runtime/sources_non_forked/padawan.vim/padawan.php/src/IO/Reader.php on line 12
```

when I triggered via Vim.

**Comment by mkusher** [comment]
@EwanValentine what message exactly do you get after `:PadawanStartServer`? If it is timeout, than try triggering completion one more time or increase timeout to 0.5s:
`let g:padawan#timeout = "0.5"`

**Comment by mkusher** [comment]
@EwanValentine it means, that padawan has reached max allowed memory, can you increase `memory_limit` flag in your php.ini to `256M` or `512M`?

**Comment by EwanValentine** [comment]
Ah, of course! Got it, thanks again!
