### ISSUE TITLE
PHP native functions

### ISSUE THREAD

**Issue by lukepass** [mkusher/padawan.vim#25]
Hello, I managed to install this plugin on my Ubuntu (I had to install vim-gnome-py2 and remove vim-gnome because of python).
I am now able to complete standard objects (such as `$this->generateRoute(/*...*/)`) but native PHP functions are not autocompleted, it keeps saying Pattern not found:

![defaultcontroller php -site t-src-appbundle-controller - gvim_004](https://cloud.githubusercontent.com/assets/6429961/19153668/bbd03106-8bd7-11e6-9af7-46d688acc7c3.jpg)

How can I fix this?
Thanks and keep up the good job on this!

**Comment by mkusher** [comment]
@lukepass this feature is only available in padawan.php#master, not in 0.2.1 version. So update your padawan.php

**Comment by lukepass** [comment]
Hello and thanks for your quick answer. I tried:

`composer global update mkusher/padawan:dev-master`

But in my composer.json there is still version 0.21. How can I update it?

**Comment by mkusher** [comment]
try

```
composer global require mkusher/padawan:dev-master
```

you'll need to update your minimum stability for global packages

**Comment by lukepass** [comment]
I lowered the minimum stability but now I get this error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: react/http[dev-master, v0.4.1].
    - Can only install one of: react/http[v0.4.1, dev-master].
    - Can only install one of: react/http[dev-master, v0.4.1].
    - don't install react/http dev-master|don't install react/react v0.4.1
    - mkusher/padawan dev-master requires react/http dev-master -> satisfiable by react/http[dev-master].
    - Installation request for mkusher/padawan dev-master -> satisfiable by mkusher/padawan[dev-master].
    - Installation request for react/http (locked at v0.4.1) -> satisfiable by react/http[v0.4.1], react/react[v0.4.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by mkusher** [comment]
remove previous version of padawan and then install new one

**Comment by lukepass** [comment]
Thanks, now I can complete native functions:

![image](https://cloud.githubusercontent.com/assets/6429961/19155646/7d769dfc-8bdf-11e6-936a-20d7fb1aa145.png)

But unfortunately it doesn't work anymore on other variables :(

![image](https://cloud.githubusercontent.com/assets/6429961/19155671/96b12fd0-8bdf-11e6-959a-3b871ebe1dfc.png)

I already tried to restart server, restart vim and regenerate index.

Thanks.

**Comment by mkusher** [comment]
oh, you have to re-run index generation

**Comment by lukepass** [comment]
Hello,
I already tried to restart server, restart vim and regenerate index.

When executing `PadawanUpdateIndex` there's an error: `Error occurred timed out`

**Comment by mkusher** [comment]
try PadawanGenerateIndex
