### ISSUE TITLE
This Vim cannot execute :python after using :py3

### ISSUE THREAD

**Issue by punknroll** [mkusher/padawan.vim#28]
Hi, when I try to run :PadawanGenerateIndex I get the following error:

This Vim cannot execute :python after using :py3

I am using Ubuntu 17.04 and vim 8.

Any hints? Thanks.

**Comment by pbogut** [comment]
This is a problem with your Vim as it can not run both `python` and `python3` (I'm not sure if that depends on build or it is general Vim issue). Probably you have another plugin that is using `python3` and this one is using `python`.  I guess this plugin could be rewritten to support both, `python` and `python3`, but currently, it does not.

**Comment by ghost** [comment]
It looks like Ubuntu dropped support for Python 2 since Zesty: https://bugs.launchpad.net/ubuntu/+source/vim/+bug/1654882

`vim-nox-py2` doesn't exists anymore too.

**Comment by mkusher** [comment]
should we just replace `python` on [this line](https://github.com/padawan-php/padawan.vim/blob/master/autoload/padawan.vim#L46) with `python3`?

**Comment by pbogut** [comment]
We can do, but you will also have to change some code to be compatible with python3. As python2 is not fully compatible with python3, this is something that I was doing when I was taking padawan.vim code to deoplete-padawan.
Plus, the plugin won't be compatible with python2 anymore, so If someone has only python2 support in vim it won't work.

**Comment by mkusher** [comment]
@pbogut as I remember, deoplete-padawan has all needed fixes to support both py2 and py3, am I right?

**Comment by ghost** [comment]
Yes that's what I did. Vim files raise no errors like this.

But I haven't fixed the padawan.py file:

- Change `import urllib2` to `from urllib.request import urlopen`
- Change `urllib2.response = urlopen` to `response = urlopen`

But I still have errors and I don't know how to fix them because it is about Vim/Python not just Python:

```
Erreur détectée en traitant function padawan#GenerateIndex :
ligne    6 :
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/damien/Projets/padawan.vim/python/padawan.py", line 245, in Generate
    editor.callAfter(1e-4, ProcessGenerationPoll)
  File "/home/damien/Projets/padawan.vim/python/padawan.py", line 77, in callAfter
    while callback():
  File "/home/damien/Projets/padawan.vim/python/padawan.py", line 231, in ProcessGenerationPoll
    errorMatch = re.search('Error: (.*)', line)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
``` 

I haven't pushed anything yet and I'm not sure it is the correct way to do... `padawan.vim` must be compatible with Vim with python 2 and 3 I think. Dropping support for python 2 would be annoying for a lot of people.

**Comment by mkusher** [comment]
@martin-damien I think there should be done smth similar to https://github.com/padawan-php/padawan.sublime/blob/master/padawan.py#L7
like @twistor did in https://github.com/padawan-php/padawan.sublime/pull/4

**Comment by pbogut** [comment]
@mkusher deoplete-padawan works only with py3, as deoplete itself works only with py3.

**Comment by Mte90** [comment]
I made a pr with fixes (works on my machine) https://github.com/padawan-php/padawan.vim/pull/30
