### ISSUE TITLE
No complete response

### ISSUE THREAD

**Issue by azzsh** [mkusher/padawan.vim#29]
I created the project file in the root directory, but there is no complete response, I was very anxious to complete the semantic configuration of God, beg God for help!

**Comment by mkusher** [comment]
can you try to debug it with `netcat`?

**Comment by azzsh** [comment]
Received the great God's reply very excited, colleagues are very ashamed, I'm a rookie, I'm using the system is Mac OS, can you point out how I should use netcat?
