### ISSUE TITLE
Use it only on php file

### ISSUE THREAD

**Issue by Mte90** [mkusher/padawan.vim#32]
I saw that padawan is executed also on html files, there is a way to disable this behaviour?

**Comment by mkusher** [comment]
what do you mean?

**Comment by Mte90** [comment]
I saw that the call to padawan (for autocomplete) is made also if I am writing on a file detected as html that not contain php code.

**Comment by mkusher** [comment]
sounds strange, because it should be only for file type `php`: https://github.com/padawan-php/padawan.vim/blob/master/after/ftplugin/php/padawan.vim

**Comment by Mte90** [comment]
Uhm you are right, seems something weird on my vimrc.
In case I have more info I will add more info there :-)

**Comment by Mte90** [comment]
Uhm seems more a problem of nvim-yarp that use a lot of memory and not of padawan.
