### ISSUE TITLE
Use with ervandew/supertab

### ISSUE THREAD

**Issue by juanperi** [mkusher/padawan.vim#4]
Do you have any idea/have you checked how to configure this plugin to be used with the supertab plugin?

**Comment by mkusher** [comment]
@epilgrim padawan.vim provides omnifunc for php, so you may want to place `let g:SuperTabDefaultCompletionType = "<c-x><c-o>"` in `ftplugin/php.vim` to get padawan's completion after pressing Tab

**Comment by juanperi** [comment]
True!! thanks!
