### ISSUE TITLE
error while calling PadawanGenerateIndex

### ISSUE THREAD

**Issue by iwyg** [mkusher/padawan.vim#8]
I get the following error message: `Error Occured, code: 255`.

Any idea?

**Comment by mkusher** [comment]
@iwyg hello, it looks like you haven't setup your PATH correctly. You should add to `~/.zprofile`, `~/.profile` or `~/.bash_profile` line like:

``` bash
PATH="$PATH:$HOME/.composer/vendor/bin"
```

also make sure you have `$HOME` env-variable

**Comment by iwyg** [comment]
No, but surprisingly installing `ext-event` fixed it. 

Thanks
